[build]
# Build command - Railway will automatically install requirements.txt
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
# Start command for your FastAPI application
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT"

# Health check configuration
healthcheckPath = "/docs"
healthcheckTimeout = 300

# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
